server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://82.157.7.158:3306/web?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/bookmanagement?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 2053703
#    password: Yangchaofan0421

#  url: jdbc:mysql://82.157.7.158:80/web?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#  url: jdbc:mysql://localhost:3306/bookmanagement?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#  # Hikari ?????
#  hikari:
#    minimum-idle: 3  # ????????
#    maximum-pool-size: 5  # ????????????10
#    max-lifetime: 1800000  # ??????????????????0???????????1800000?30??
#    connection-test-query: SELECT 1